Repository mju-likelion/mju-festival-frontend, pull requests merged in 2024-09, with the labels that each got.

#40 [Feature/#39] 로그인 로직 리팩터링
  src/App.tsx
  src/hooks/useDetermineRole.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/Main/index.tsx
  src/utils/downloadAppUtil.ts
  src/utils/encryptionUtil.ts
  src/utils/errorUtil.ts
Labels: 🧹 refactor

#42 [Feature/#35] 분실물 API 연동 리팩터링
  src/App.tsx
  src/api/lostItem.ts
  src/pages/CreateLostItem/index.tsx
  src/pages/Main/index.tsx
  src/pages/ViewAllLostItem/LostItemCard.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewDetailLostItem/index.tsx
Labels: 🧹 refactor

#49 [Feature/#48] mobile wrapper 구현
  src/App.tsx
  src/hooks/useScreenSize.ts
Labels: 💖 feature

#57 [Feature/#45] 로그인페이지 스타일
  .eslintrc.cjs
  src/App.tsx
  src/assets/icons/checkbox_check.svg
  src/assets/icons/checkbox_empty.svg
  src/assets/icons/checked.png
  src/assets/icons/left_arrow.svg
  src/assets/icons/pwd_close.svg
  src/assets/icons/pwd_open.svg
  src/assets/icons/right_arrow.svg
  src/assets/icons/unchecked.png
  src/assets/imgs/logo.svg
  src/assets/imgs/logo_subtitle.svg
  src/main.tsx
  src/pages/LogIn/CheckBox.tsx
  src/pages/LogIn/LogInButton.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/LogIn/LogInInput.tsx
  src/pages/LogIn/indexAdmin.tsx
  src/pages/LogIn/indexUser.tsx
  src/styles/GlobalStyle.ts
  src/styles/colors.ts
  src/styles/font.css
  src/styles/typographies.ts
Labels: 🎨 design

#63 [Feature/#34] floating action button 구현
  src/api/booth.ts
  src/assets/imgs/menu_camera_img.svg
  src/assets/imgs/menu_default_img.svg
  src/assets/imgs/menu_stamp_img.svg
  src/components/FloatingButton/index.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/ViewAllLostItem/index.tsx
Labels: 🎨 design

#65 [Feature/#47] 공지사항 작성 페이지 디자인
  src/assets/icons/backIcon.svg
  src/assets/icons/hamburgerMenu.svg
  src/pages/BoothList/index.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditNotice/index.tsx
  src/pages/ViewDetailNotice/Header.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/styles/GlobalStyle.ts
Labels: 🎨 design

#72 [Feature/#58] 분실물 전체 조회 페이지 스타일링
  src/App.tsx
  src/assets/icons/down_arrow.svg
  src/assets/icons/hamburger.svg
  src/assets/icons/left_arrow_active.svg
  src/assets/icons/right_arrow_active.svg
  src/assets/icons/search_input.svg
  src/assets/icons/up_arrow.svg
  src/components/FloatingButton/index.tsx
  src/components/Header.tsx
  src/components/InfoText.tsx
  src/pages/ViewAllLostItem/Header.tsx
  src/pages/ViewAllLostItem/ItemList.tsx
  src/pages/ViewAllLostItem/LostItemCard.tsx
  src/pages/ViewAllLostItem/Page.tsx
  src/pages/ViewAllLostItem/SearchInput.tsx
  src/pages/ViewAllLostItem/SortDropDown.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/styles/colors.ts
Labels: 🎨 design

#73 [Feature/#59] 분실물 상세 조회 페이지 스타일링
  src/api/lostItem.ts
  src/assets/icons/close.svg
  src/assets/icons/noData.svg
  src/assets/icons/place.svg
  src/components/Header.tsx
  src/pages/EditLostItem/index.tsx
  src/pages/LogIn/indexUser.tsx
  src/pages/ViewAllLostItem/ItemList.tsx
  src/pages/ViewAllLostItem/LostItemCard.tsx
  src/pages/ViewAllLostItem/Modal.tsx
  src/pages/ViewAllLostItem/SearchInput.tsx
  src/pages/ViewAllLostItem/SortDropDown.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewDetailLostItem/Header.tsx
  src/pages/ViewDetailLostItem/Modal.tsx
  src/pages/ViewDetailLostItem/index.tsx
  src/styles/colors.ts
  src/utils/dateUtil.ts
Labels: 🎨 design

#74 [Feature/#69] 타임테이블 페이지 구현 및 스타일링
  src/App.tsx
  src/assets/imgs/timetable_plant.png
  src/assets/team_imgs/timetable_infoimg.png
  src/context/TimeTable.tsx
  src/pages/Main/index.tsx
  src/pages/TimeTable/DetailInfo.tsx
  src/pages/TimeTable/DetailInfoList.tsx
  src/pages/TimeTable/TypeIcon.tsx
  src/pages/TimeTable/index.tsx
  src/types/index.ts
  src/types/timetable.ts
Labels: 🎨 design, 💖 feature

#76 [Feature/#55] 공지 상세페이지 스타일링 및 기능 보완
  src/assets/icons/no_image_icon.svg
  src/pages/Main/index.tsx
  src/pages/ViewDetailNotice/DeleteNoticeModal.tsx
  src/pages/ViewDetailNotice/NoImage.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/types/notice.ts
  src/utils/openInstaUtil.ts
Labels: 🎨 design, 💖 feature

#79 [Feature/#68] 공지 수정페이지 스타일링 및 기능 보완
  src/pages/CreateNotice/index.tsx
  src/pages/EditNotice/index.tsx
Labels: 🎨 design

#80 [Feature/#67] 공지 전체 조회 페이지 스타일링
  src/pages/ViewAllNotice/NoticeCard.tsx
  src/pages/ViewAllNotice/index.tsx
Labels: 🎨 design

#77 [Feature/#75] 분실물 작성/수정 페이지 스타일링
  src/pages/CreateLostItem/FormActions.tsx
  src/pages/CreateLostItem/Header.tsx
  src/pages/CreateLostItem/ImageUploader.tsx
  src/pages/CreateLostItem/LostItemFormFields.tsx
  src/pages/CreateLostItem/index.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditLostItem/FormActions.tsx
  src/pages/EditLostItem/ImageUploader.tsx
  src/pages/EditLostItem/LostItemFormFields.tsx
  src/pages/EditLostItem/index.tsx
  src/validation/schema.ts
Labels: 🎨 design

#81 [Feature/#64] 부스 무한스크롤 구현 및 스타일 적용
  package.json
  src/api/booth.ts
  src/assets/icons/booth-checked.svg
  src/assets/icons/booth-un-checked.svg
  src/assets/icons/checked.png
  src/assets/icons/location_icon.svg
  src/assets/icons/unchecked.png
  src/main.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/LogIn/LogInInput.tsx
  src/pages/LogIn/indexAdmin.tsx
  src/pages/LogIn/indexUser.tsx
  src/styles/GlobalStyle.ts
  src/types/auth.ts
  src/types/booth.ts
  yarn.lock
Labels: 🎨 design, 💖 feature

#83 [Feature/#71] 메인 페이지 스타일링
  src/assets/icons/footer_home_icon.svg
  src/assets/icons/footer_link_icon.svg
  src/assets/icons/footer_mju_logo.svg
  src/context/TimeTable.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/Main/Header.tsx
  src/pages/Main/index.tsx
Labels: 🎨 design

#88 [Feature/#87] logout
  src/pages/BoothDetail/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/LogIn/LogInInput.tsx
  src/pages/Main/Header.tsx
  src/pages/Map/index.tsx
  src/pages/TimeTable/index.tsx
  src/pages/ViewAllNotice/Header.tsx
  src/pages/ViewAllNotice/index.tsx
  src/pages/ViewDetailNotice/index.tsx
Labels: 🎨 design, 💖 feature

#95 [Feature/#94] 날씨 API 연결
  src/api/Axios.ts
  src/api/stamp.ts
  src/api/weather.ts
  src/assets/icons/weather_cloud.svg
  src/assets/icons/weather_error.svg
  src/assets/icons/weather_rainy.svg
  src/assets/icons/weather_sunny.svg
  src/pages/CreateNotice/index.tsx
  src/pages/Main/Weather.tsx
  src/pages/Main/index.tsx
  src/pages/Stamp/Board.tsx
  src/pages/ViewDetailLostItem/index.tsx
  src/types/main.ts
  src/utils/dateUtil.ts
Labels: 🎨 design, 💖 feature

#96 feat: 각 부서에 대한 무한스크롤 기능 구현 - #93
  src/api/booth.ts
  src/pages/BoothList/index.tsx
  src/types/booth.ts
Labels: 💖 feature

#99 [Feature/#61] QR 발급 및 인식 기능 구현
  package.json
  src/App.tsx
  src/api/booth.ts
  src/assets/icons/sheet_down_arrow.svg
  src/assets/icons/sheet_up_arrow.svg
  src/assets/imgs/camera_outline.svg
  src/assets/imgs/camera_outline_bottom_left.svg
  src/assets/imgs/camera_outline_bottom_right.svg
  src/assets/imgs/camera_outline_top_left.svg
  src/assets/imgs/camera_outline_top_right.svg
  src/assets/imgs/menu_camera.svg
  src/assets/imgs/menu_camera_img.svg
  src/assets/imgs/menu_default.svg
  src/assets/imgs/menu_stamp.svg
  src/assets/imgs/menu_stamp_img.svg
  src/assets/imgs/sheet_back_close.png
  src/assets/imgs/sheet_back_open.png
  src/assets/imgs/sheet_small_qr.svg
  src/components/FloatingButton/index.tsx
  src/components/QrBottomSheet/BottomSheetOption.ts
  src/components/QrBottomSheet/Content.tsx
  src/components/QrBottomSheet/Header.tsx
  src/components/QrBottomSheet/index.tsx
  src/hooks/useBottomSheet.ts
  src/pages/BoothDetail/index.tsx
  src/pages/QrReader/index.tsx
  src/types/booth.ts
  yarn.lock
Labels: 🎨 design, 💖 feature

#100 [Feature/#89] 공지사항 이탈 후 페이지 오류
  src/components/Header.tsx
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/index.tsx
Labels: 🪚 fix, 🎨 design

#110 [Feature/#92] 부스 이미지 수정
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/types/booth.ts
  src/validation/schema.ts
Labels: 🎨 design, 💖 feature

#107 [Feature/#97] Landing page 구현
  package.json
  src/App.tsx
  src/assets/icons/landing_right_arrow.svg
  src/assets/imgs/landing_Bg.webp
  src/assets/imgs/landing_header_content.svg
  src/assets/imgs/landing_mju_logo.svg
  src/assets/imgs/landing_title.svg
  src/pages/Landing/Layout.tsx
  src/pages/Landing/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/LogIn/indexAdmin.tsx
  src/pages/LogIn/indexUser.tsx
  src/pages/Main/index.tsx
  src/pages/StampComplete/index.tsx
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/index.tsx
  yarn.lock
Labels: 🎨 design, 💖 feature

#112 [Feature/#109] QR 관련 코드 수정 및 리팩토링
  index.html
  package.json
  src/api/booth.ts
  src/assets/icons/qr_refresh.svg
  src/components/FloatingButton/index.tsx
  src/components/QrBottomSheet/Content.tsx
  src/components/QrBottomSheet/index.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/LogIn/CheckBox.tsx
  src/pages/Main/index.tsx
  src/pages/QrReader/index.tsx
  src/types/booth.ts
  yarn.lock
Labels: 🪚 fix, 🧹 refactor

#113 [Feature/#85] OG 태그 설정
  index.html
  public/og_image.png
  src/components/Header.tsx
  src/pages/Landing/index.tsx
  src/pages/ViewAllNotice/DropDown.tsx
Labels: 💖 feature

#115 [Feature/#114] OG 태그 수정
  index.html
  public/favicon.svg
Labels: 🪚 fix

#120 [Feature/#118] 공통 컴포넌트 헤더 라우팅 수정
  index.html
  src/api/booth.ts
  src/components/Header.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/CreateLostItem/FormActions.tsx
  src/pages/CreateLostItem/index.tsx
  src/pages/EditLostItem/index.tsx
  src/pages/Main/Header.tsx
  src/pages/Map/index.tsx
  src/pages/QrReader/index.tsx
  src/pages/Setting/Header.tsx
  src/pages/Setting/index.tsx
  src/pages/Stamp/Board.tsx
  src/pages/Stamp/index.tsx
  src/pages/TimeTable/index.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewAllNotice/index.tsx
  src/pages/ViewDetailLostItem/index.tsx
Labels: 🪚 fix

#123 [Feature/#111] 로그인 UI 수정
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/LogIn/LogInButton.tsx
  src/pages/LogIn/LogInForm.tsx
  src/styles/colors.ts
  src/utils/errorUtil.ts
Labels: 🎨 design, 💖 feature

#124 [Feature/#121] 날씨 컴포넌트 예외처리 추가
  index.html
  src/pages/EditLostItem/index.tsx
  src/pages/Main/Weather.tsx
Labels: 🪚 fix, 🧹 refactor

#126 [Feature/#125] 공통 컴포넌트 Footer 동적으로 바텀 고정
  src/App.tsx
  src/components/Footer/index.tsx
  src/pages/Landing/Layout.tsx
Labels: 🪚 fix

#119 [Feature/#116] 부스 리스트 조회 페이징 삭제
  package.json
  src/api/booth.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothList/index.tsx
  src/types/booth.ts
  yarn.lock
Labels: 🧹 refactor, 💖 feature

#122 [Feature/#117] 공지사항 예외처리 및 리팩터링
  src/components/LoadingSpinner.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditNotice/index.tsx
  src/pages/Main/index.tsx
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/TitleLayout.tsx
  src/pages/ViewAllNotice/index.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/store/index.ts
  src/store/notice.ts
Labels: 🪚 fix, 🧹 refactor

#132 [Feature/#127] 디테일한 스타일 수정
  src/api/booth.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/styles/GlobalStyle.ts
Labels: 🪚 fix, 🎨 design

#134 [Feature/#133] 잘못된 접근 방지
  src/App.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/Main/Header.tsx
  src/pages/NotFound/index.tsx
  src/pages/Setting/index.tsx
  src/utils/errorUtil.ts
Labels: 🎨 design, 💖 feature

#136 [Feature/#106] 도장판 페이지 수정 및 리팩토링
  src/assets/icons/weather_cloud.svg
  src/assets/icons/weather_day_cloud.svg
  src/assets/icons/weather_day_rainy.svg
  src/assets/icons/weather_day_sunny.svg
  src/assets/icons/weather_night_cloud.svg
  src/assets/icons/weather_night_moon.svg
  src/assets/icons/weather_night_rainy.svg
  src/assets/icons/weather_rainy.svg
  src/assets/icons/weather_sunny.svg
  src/components/FloatingButton/index.tsx
  src/components/QrBottomSheet/Content.tsx
  src/pages/Main/Weather.tsx
  src/pages/Stamp/Board.tsx
  src/pages/ViewAllLostItem/Page.tsx
Labels: 🪚 fix

#137 [Feature/#135] 부스 로딩 상태 추가
  src/hooks/useFetchNotices.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
Labels: 💖 feature

#140 [Feature/#138] 탈퇴 로직 수정
  src/pages/Setting/index.tsx
Labels: 🪚 fix

#145 [Feature/#139] 각 페이지 오류 수정 및 UI 변경사항 반영
  src/assets/icons/big_error.svg
  src/components/QrBottomSheet/Content.tsx
  src/components/QrBottomSheet/index.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/CreateLostItem/index.tsx
  src/pages/EditLostItem/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/QrReader/index.tsx
  src/pages/Setting/index.tsx
  src/pages/Stamp/Board.tsx
  src/pages/Stamp/index.tsx
  src/pages/StampComplete/index.tsx
  src/pages/ViewAllLostItem/SortDropDown.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/index.tsx
  src/pages/ViewDetailLostItem/Modal.tsx
  src/pages/ViewDetailLostItem/index.tsx
  src/utils/errorUtil.ts
  src/validation/schema.ts
Labels: 🪚 fix, 🎨 design
