Repository mju-likelion/mju-festival-frontend, pull requests merged in 2024-10, with the labels that each got.

#143 [Feature/#142] 타임테이블 스타일링
  src/App.tsx
  src/assets/imgs/timetable_dash.svg
  src/assets/imgs/timetable_dashed.svg
  src/assets/imgs/timetable_hr.svg
  src/assets/team_imgs/10cm.png
  src/assets/team_imgs/carthegarden.png
  src/assets/team_imgs/changmo.png
  src/assets/team_imgs/heize.png
  src/assets/team_imgs/punch.png
  src/assets/team_imgs/yena.png
  src/context/TimeTable.tsx
  src/pages/Main/index.tsx
  src/pages/TimeTable/CelebrityPerformance.tsx
  src/pages/TimeTable/ClubPerformance.tsx
  src/pages/TimeTable/DetailInfo.tsx
  src/pages/TimeTable/DetailInfoList.tsx
  src/pages/TimeTable/InfoTitle.tsx
  src/pages/TimeTable/TypeIcon.tsx
  src/pages/TimeTable/UnivPerformance.tsx
  src/pages/TimeTable/index.tsx
  src/pages/ViewAllNotice/index.tsx
  src/types/timetable.ts
Labels: 🎨 design

#148 [Feature/#141] 스타일 수정
  src/components/Footer/ContentLayout.tsx
  src/components/Footer/index.tsx
  src/pages/LogIn/indexUser.tsx
  src/pages/QrReader/index.tsx
  src/pages/TimeTable/CelebrityPerformance.tsx
  src/pages/TimeTable/ClubPerformance.tsx
  src/styles/typographies.ts
Labels: 🪚 fix, 🎨 design

#152 [Feature/#151] 1차 배포
  index.html
  package.json
  public/favicon.svg
  public/og_image.png
  src/App.tsx
  src/assets/icons/landing_right_arrow.svg
  src/assets/imgs/landing_Bg.webp
  src/assets/imgs/landing_header_content.svg
  src/assets/imgs/landing_mju_logo.svg
  src/assets/imgs/landing_title.svg
  src/assets/react.svg
  src/hooks/useScreenSize.ts
  src/main.tsx
  src/pages/Landing/Layout.tsx
  src/pages/Landing/index.tsx
  src/styles/GlobalStyle.ts
  yarn.lock
Labels: 💖 feature

#153 [Feature/#151] 1차 배포
  public/_redirects
  src/App.tsx
  src/assets/icons/big_error.svg
  src/pages/NotFound/index.tsx
Labels: 💖 feature

#150 [Feature/#149] 로직 수정
  src/pages/LogIn/LogInForm.tsx
  src/pages/ViewDetailLostItem/index.tsx
Labels: 🪚 fix

#131 [Feature/#128] 인증 관련 및 공지사항 페이지 예외처리
  .eslintrc.cjs
  package.json
  src/api/Axios.ts
  src/components/ErrorMessage.tsx
  src/components/LoadingSpinner.tsx
  src/hooks/useErrorHandler.ts
  src/hooks/useFetchNotices.ts
  src/main.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditNotice/index.tsx
  src/pages/TimeTable/ClubPerformance.tsx
  src/pages/TimeTable/index.tsx
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/NoticeContent.tsx
  src/pages/ViewAllNotice/index.tsx
  src/pages/ViewDetailNotice/DeleteNoticeModal.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/store/error.ts
  src/store/index.ts
  src/types/errorCode.ts
  src/types/index.ts
  src/types/notice.ts
  yarn.lock
Labels: 🧹 refactor, 💖 feature

#147 [Feature/#144] 메인 페이지 애니메이션 수정
  src/pages/Main/index.tsx
Labels: 🪚 fix, 🎨 design

#157 [Feature/#156] 부스 리스트 API response 변경사항에 맞게 수정
  src/api/booth.ts
  src/types/booth.ts
Labels: 🧹 refactor

#160 [Feature/#158] 부스 description만 수정 가능하도록 변경
  src/api/booth.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/types/booth.ts
  src/validation/schema.ts
Labels: 🧹 refactor

#162 [Feature/#159] 분실물, 공지사항 페이지에 작성 시각도 표현하도록 변경
  src/pages/ViewDetailLostItem/index.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/utils/dateUtil.ts
Labels: 🧹 refactor

#166 [Feature/#164] 공지사항 뒤로가기 페이지 스택 이슈
  src/pages/ViewAllNotice/DropDown.tsx
  src/pages/ViewAllNotice/index.tsx
Labels: 🪚 fix

#165 fix: 로그인 된 상태에서는 '로그인페이지' 버튼이 노출되지 않도록 수정 - #161
  src/assets/icons/stamp.svg
  src/pages/BoothDetail/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/Setting/index.tsx
  src/types/booth.ts
Labels: 🎨 design, 💖 feature

#168 [Feature/#167] 분실물 상세조회 API 반영
  src/api/lostItem.ts
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/EditLostItem/index.tsx
  src/pages/ViewDetailLostItem/index.tsx
Labels: 💖 feature

#169 [Feature/#163] timetable 이미지 수정
  src/assets/icons/map_booth_icon.svg
  src/assets/icons/map_event_icon.svg
  src/assets/icons/map_foodtruck_icon.svg
  src/assets/icons/map_mic_icon.svg
  src/assets/imgs/map1.webp
  src/assets/imgs/map2_1.webp
  src/assets/imgs/map3_1.webp
  src/pages/Map/index.tsx
  src/pages/TimeTable/CelebrityPerformance.tsx
Labels: 🎨 design

#171 [Refactor/#155] 프로덕션 릴리스를 위한 전체 버그 수정
  src/api/Axios.ts
  src/components/ErrorMessage.tsx
  src/components/Header.tsx
  src/hooks/useErrorHandler.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditNotice/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/Main/Weather.tsx
  src/pages/QrReader/index.tsx
  src/pages/Stamp/Board.tsx
  src/pages/ViewAllLostItem/ItemList.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewAllNotice/NoticeContent.tsx
  src/pages/ViewDetailLostItem/index.tsx
  src/pages/ViewDetailNotice/DeleteNoticeModal.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/store/error.ts
  src/store/index.ts
  src/types/errorCode.ts
  src/types/index.ts
  src/utils/errorUtil.ts
  vite.config.dev.ts.timestamp-1727898171897-70b4b43e8f24b.mjs
Labels: 🪚 fix, 🧹 refactor, 🎨 design

#173 [Refactor/#172] handleError 로직 axios interceptors로 병합
  src/api/Axios.ts
  src/api/postLogIn.ts
  src/pages/BoothDetail/index.tsx
  src/pages/BoothEdit/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/CreateLostItem/index.tsx
  src/pages/CreateNotice/index.tsx
  src/pages/EditLostItem/index.tsx
  src/pages/EditNotice/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/Main/index.tsx
  src/pages/QrReader/index.tsx
  src/pages/Setting/index.tsx
  src/pages/Stamp/Board.tsx
  src/pages/ViewAllLostItem/index.tsx
  src/pages/ViewAllNotice/NoticeContent.tsx
  src/pages/ViewDetailLostItem/index.tsx
  src/pages/ViewDetailNotice/DeleteNoticeModal.tsx
  src/pages/ViewDetailNotice/index.tsx
  src/utils/date/dateUtil.ts
  src/utils/date/format/DateAndTimeFormat.ts
  src/utils/date/format/DateFormat.ts
  src/utils/date/format/DateOnlyFormat.ts
  src/utils/dateUtil.ts
Labels: 🪚 fix, 🧹 refactor, 💖 feature

#175 [Feature/#174] 학생 로그인일 경우에만 terms를 요청 하도록 수정
  src/pages/LogIn/LogInForm.tsx
Labels: 🧹 refactor

#177 [Feature/#176] Production Google Analytics 추가
  .gitignore
  src/App.tsx
  src/hooks/useRouteTracker.tsx
Labels: ⚙️ setting

#178 [Feature/#170] fix notice css
  src/assets/imgs/landing_Bg.webp
  src/pages/EditNotice/index.tsx
  src/pages/Landing/index.tsx
Labels: 🧹 refactor, 🎨 design

#180 [Feature/#179] notice 이미지 css 수정
  src/pages/EditNotice/index.tsx
Labels: 🎨 design

#182 [Feature/#181] 스타일 수정
  src/components/FloatingButton/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/LogIn/LogInForm.tsx
  src/pages/ViewAllLostItem/SearchInput.tsx
Labels: 🎨 design

#185 [Feature/#86] sentry 설정
  package.json
  src/main.tsx
  yarn.lock
Labels: 💖 feature

#186 [Refactor/#184] 프로덕션 릴리스를 위한 2차 전체 버그 수정
  src/App.tsx
  src/pages/CreateLostItem/index.tsx
  src/pages/EditLostItem/index.tsx
Labels: 🪚 fix, 🧹 refactor

#190 [Feature/#183] fix css
  src/pages/BoothList/index.tsx
  src/pages/CreateLostItem/ImageUploader.tsx
  src/pages/EditLostItem/ImageUploader.tsx
  src/pages/Landing/index.tsx
  src/pages/LogIn/indexAdmin.tsx
  src/pages/LogIn/indexUser.tsx
  src/pages/ViewAllNotice/NoticeCard.tsx
  src/pages/ViewDetailLostItem/index.tsx
Labels: 🎨 design

#200 [Hotfix/#199 timetable data 수정
  src/pages/TimeTable/CelebrityPerformance.tsx
Labels: 🪚 fix

#202 [Hotfix/#201] 부스 방문 API 연결 함수/전체 스타일링 수정 hotfix
  index.html
  public/og_image.png
  src/App.tsx
  src/assets/icons/boothStampIcon.svg
  src/components/FloatingButton/index.tsx
  src/pages/BoothDetail/index.tsx
  src/pages/BoothList/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Map/index.tsx
  src/pages/QrReader/index.tsx
  src/pages/Setting/index.tsx
  src/pages/Stamp/index.tsx
  src/pages/TimeTable/CelebrityPerformance.tsx
  src/pages/ViewDetailLostItem/Modal.tsx
  src/pages/ViewDetailLostItem/index.tsx
  vite.config.dev.ts.timestamp-1728142308959-6d005a775d978.mjs
Labels: 🚨 hotfix

#203 2차 배포
  src/pages/BoothDetail/index.tsx
  src/pages/QrReader/index.tsx
  src/pages/Setting/index.tsx
  src/pages/Stamp/index.tsx
Labels: 🍀 deploy
